name: robot_chronicles
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  xor_dart: ^1.0.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  xml: ^6.5.0
  shelf_static: ^1.1.3
  uuid: ^4.5.1
  http: ^1.4.0
  collection: ^1.19.1

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^8.0.0

dependency_overrides:
  xor_dart:
    path: ../xor.dart
